name: Run PyInstaller
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: false
          activate-environment: py310_cmautoeditor
          environment-file: conda_requirements_py310.txt
    - run: conda install -c conda-forge pyinstaller
    - run: python -m PyInstaller --noconfirm --log-level=INFO --clean build.spec
    - run: python -m PyInstaller --noconfirm --log-level=INFO --clean --onefile --hidden-import matplotlib.backends.backend_svg .\osm2cm.py
    - run: copy LICENSE dist/LICENSE
    - run: copy README.md dist/README.md
    - run: copy example_height_map.csv dist/example_height_map.csv
    - run: copy default_osm_config.json dist/default_osm_config.json
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: dist/*
