name: Run PyInstaller
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
          run:
            shell: bash -el {0}    
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: false
          activate-environment: py310_cmautoeditor
          channels: conda-forge
          python-version: "3.10"
    - run: conda install --file requirements.txt
    - run: python -m PyInstaller --noconfirm --log-level=INFO --clean build.spec
    - run: python -m PyInstaller --noconfirm --log-level=INFO --clean --onefile --hidden-import matplotlib.backends.backend_svg .\osm2cm.py
    - run: copy LICENSE dist/LICENSE
    - run: copy README.md dist/README.md
    - run: copy example_height_map.csv dist/example_height_map.csv
    - run: copy default_osm* dist/
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: dist/*
