name: Run PyInstaller
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: false
          activate-environment: py38_cmautoeditor
          environment-file: conda_requirements_py38.txt

    - run: conda install -c conda-forge pyinstaller
    - run: pyinstaller --noconfirm --log-level=INFO --clean build.spec
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: dist/*.exe
        path: example_height_map.csv
        path: LICENSE
        path: README.md